---
version: '2'

services:
  alert-pathways:
    environment:
      - 'ARTIFACTORY_PW=${ARTIFACTORY_PW}'
      - 'PROJECT_NAME=${CIRCLE_PROJECT_REPONAME}'
      - 'TOWER_PASSWORD=${TOWER_PASSWORD}'
      - 'SENTRY_ENABLED=${SENTRY_ENABLED}'
      - 'SENTRY_DSN_KEY=${SENTRY_DSN_KEY}'
      - 'SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}'
      - 'EXPEL_ENGINEERING_SIGNING_KEY=${EXPEL_ENGINEERING_SIGNING_KEY}'
      - 'EXPEL_ENGINEERING_SIGNING_PASSPHRASE=${EXPEL_ENGINEERING_SIGNING_PASSPHRASE}'
      - 'CIRCLE_PROJECT_REPONAME=${CIRCLE_PROJECT_REPONAME}'
      - 'CIRCLE_TAG=${CIRCLE_TAG}'
    build: .
    volumes:
      - .:/app
